config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('donations.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

donations/urls.py
from django.urls import path

from . import views

app_name = 'donations'

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing_page'),
    path('donation', views.AddDonationView.as_view(), name='add_donation'),
    path('donation-is-taken/<int:donation_id>', views.DonationIsTakenView.as_view(), name='donation_taken'),
    path('donation/success', views.SuccessAddDonationView.as_view(), name='success_add_donation'),
    path('login', views.DonationsLoginView.as_view(), name='login'),
    path('logout', views.DonationsLogoutView.as_view(), name='logout'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('profile', views.UserProfileView.as_view(), name='user_profile'),
    # path('edit', views.edit_user_profile_view, name='user_change'),
]

donations/models.py
from django.contrib.auth import get_user_model
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField

from . import enums


class Category(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class Institution(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    type = models.SmallIntegerField(choices=enums.OrganisationType.CHOICES, default=0)
    categories = models.ManyToManyField('Category', related_name='institutions')

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.SmallIntegerField()
    categories = models.ManyToManyField('Category', related_name='donations')
    institution = models.ForeignKey('Institution', on_delete=models.PROTECT, related_name='donations')
    address = models.CharField(max_length=64)
    phone_number = PhoneNumberField(null=False, blank=False)
    city = models.CharField(max_length=64)
    zip_code = models.CharField(max_length=6)
    picup_date = models.DateField()
    picup_time = models.TimeField()
    picup_comment = models.TextField()
    user = models.ForeignKey(get_user_model(), null=True, on_delete=models.PROTECT)
    is_taken = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user} {self.institution}'

donations/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db.models.functions import Length
from django.shortcuts import redirect
from django.urls import reverse_lazy

from phonenumber_field.formfields import PhoneNumberField

from . import models


class UserRegisterForm(UserCreationForm):
    password1 = forms.CharField(max_length=20, widget=forms.PasswordInput(
        attrs={'name': 'password', 'placeholder': 'Hasło'}))

    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(
        attrs={'name': 'password2', 'placeholder': 'Powtórz hasło'}))

    email = forms.CharField(max_length=34, widget=forms.EmailInput(attrs={'name': 'email', 'placeholder': 'Email'}))

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name']
        widgets = {
            'first_name': forms.TextInput(attrs={'name': 'name', 'placeholder': 'Imię'}),
            'last_name': forms.TextInput(attrs={'name': 'surname', 'placeholder': 'Nazwisko'}),
        }

    field_order = ['first_name', 'last_name', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = user.email
        user.is_active = True
        if commit:
            user.save()
            return user


class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    username = forms.EmailInput()
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(
        attrs={'name': 'password', 'placeholder': 'Hasło'}))

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'password']


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(max_length=34, widget=forms.EmailInput(attrs={'name': 'email', 'placeholder': 'Email'}))
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(
        attrs={'name': 'password', 'placeholder': 'Hasło'}))

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                return redirect(reverse_lazy('donations:register'))
        return super(UserLoginForm, self).clean()


class AddDonationForm(forms.ModelForm):
    phone_number = PhoneNumberField(widget=forms.TextInput(attrs={'name': 'phone', 'type': 'phone'}))

    class Meta:
        model = models.Donation
        fields = [
            'categories',
            'quantity',
            'institution',
            'address',
            'city',
            'zip_code',
            'picup_date',
            'picup_time',
            'picup_comment',
        ]

donations/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView
from django.db.models import Sum
from django.db.models.functions import Length


from random import sample

from django.views.generic.edit import FormMixin, UpdateView, FormView

from . import models, forms


class LandingPageView(TemplateView):
    template_name = "donations/index.html"

    def get_context_data(self, **kwargs):
        context = super(LandingPageView, self).get_context_data(**kwargs)
        foundations = list(models.Institution.objects.filter(type=0).order_by('name'))
        listed_foundations = sample(foundations, 3)
        non_gov_org = list(models.Institution.objects.filter(type=1).order_by('name'))
        listed_non_gov_org = sample(non_gov_org, 3)
        fund_raisers = list(models.Institution.objects.filter(type=2).order_by('name'))
        listed_fund_raisers = sample(fund_raisers, 3)
        try:
            context['donations_quantity'] = models.Donation.objects.all().aggregate(Sum('quantity'))['quantity__sum']
            context['institutions'] = models.Institution.objects.all().count()
            context['three_foundations'] = listed_foundations
            context['three_non_gov_org'] = listed_non_gov_org
            context['three_fund_raisers'] = listed_fund_raisers
            context['css_class'] = 'header--main-page'
        except models.Donation.DoesNotExist or models.Institution.DoesNotExist:
            context['donations_quantity'] = None
            context['institutions'] = None
        return context


class AddDonationView(LoginRequiredMixin, FormMixin, View):
    login_url = reverse_lazy('donations:login')
    form_class = forms.AddDonationForm

    def get(self, request):
        category_ids = self.request.GET.getlist('category_ids')
        categories = models.Category.objects.all().order_by(Length('name')).reverse()
        institutions = models.Institution.objects.all()
        if len(category_ids) != 0 and category_ids is not None:
            for cat_id in category_ids:
                institutions = institutions.filter(categories__id__in=[cat_id])
            return render(request, 'api_institutions.html', {'css_class': 'header--form-page', categories: 'categories', 'institutions': institutions, 'form': self.form_class})

        return render(request, 'donations/form.html', {'css_class': 'header--form-page', 'categories': categories, 'institutions': institutions, 'form': self.form_class})

    def post(self, request):
        form = forms.AddDonationForm(self.request.POST)

        # print(request.POST)
        # print(form.is_valid(), form.errors)
        # print(institution)
        if form.is_valid():
            donation = form.save(commit=False)
            donation.user = request.user
            donation.phone_number = request.POST['phone_number']
            donation.save()
            donation.categories.set(request.POST.getlist('categories'))
            return redirect('donations:success_add_donation')
        else:
            return render(request, 'donations/form.html', {'form': form})


# def edit_user_profile_view(request):
#     if request.method == 'POST':
#         form = forms.UserUpdateForm(request.POST, instance=request.user)
#         if form.is_valid():
#             if form.cleaned_data['first_name'] != request.user.first_name:
#                 form.save()
#             if form.cleaned_data['last_name'] != request.user.last_name:
#                 form.save()
#             if form.cleaned_data['username'] != request.user.username;
#                 username = form.save(commit=False)
#
#
#             return redirect(reverse_lazy('donations:user_profile'))
#     else:
#         form = forms.UserUpdateForm(instance=request.user)
#         return render(request, 'donations/user-edit-form.html', {'form': form})


class DonationsLoginView(LoginView):

    template_name = 'donations/login.html'
    authentication_form = forms.UserLoginForm

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(self.request, form.get_user())
                return redirect(reverse_lazy('donations:landing_page'))
        else:
            return redirect(reverse_lazy('donations:register'))


class DonationsLogoutView(LogoutView):
    next_page = reverse_lazy('donations:landing_page')


class RegisterView(SuccessMessageMixin, CreateView):
    template_name = 'donations/register.html'
    success_url = reverse_lazy('donations:login')
    form_class = forms.UserRegisterForm
    success_message = 'Twoje konto zostało stworzone'


class SuccessAddDonationView(TemplateView):
    template_name = 'donations/form-confirmation.html'


class UserProfileView(LoginRequiredMixin, View):
    login_url = reverse_lazy('donations:login')

    def get(self, request):
        user = request.user
        user_donations = models.Donation.objects.filter(user_id=request.user).order_by('is_taken', 'picup_date')
        return render(request, 'donations/user_profile.html', {'user': user, 'donations': user_donations})


class DonationIsTakenView(LoginRequiredMixin, View):
    login_url = reverse_lazy('donations:login')

    def get(self, request, donation_id):
        donation = get_object_or_404(models.Donation, pk=donation_id)
        donation.is_taken = True
        donation.save()
        return redirect(reverse_lazy('donations:user_profile'))

donations/templates/donations/form-confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Sukces!
{% endblock %}

{% block container %}
{#    <div class="slogan container container--90">#}
{#        <h2>#}
{#            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie#}
{#            informacje o odbiorze.#}
{#        </h2>#}
{#    </div>#}
{% endblock %}

donations/templates/donations/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Formularz
{% endblock %}

{% block container %}
    <section class="form--steps">
        <div class="form--steps-instructions">
            <div class="form--steps-container">
                <h3>Ważne!</h3>
                <p data-step="1" class="active">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="2">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="3">
                    Wybierz jedną, do
                    której trafi Twoja przesyłka.
                </p>
                <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
            </div>
        </div>

        <div class="form--steps-container">
            <div class="form--steps-counter">Krok <span>1</span>/5</div>

            <form action="form-confirmation.html" method="POST" enctype="multipart/form-data" id="addDonation">
                <!-- STEP 1: class .active is switching steps -->
                {% csrf_token %}
                <div data-step="1" class="active">
                    <h3>Zaznacz co chcesz oddać:</h3>
                    {% for category in categories %}
                    <div class="form-group form-group--checkbox">
                        <label>
                            <input
                                    type="checkbox"
                                    name="categories"
                                    value="{{ category.id }}"
                                    id="category-checkbox"
                            />
                            <span class="checkbox"></span>
                            <span class="description"
                            >{{ category.name }}</span
                            >
                        </label>
                    </div>
                    {% endfor %}

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 2 -->
                <div data-step="2">
                    <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

                    <div class="form-group form-group--inline">
                        <label>
                            Liczba 60l worków:
                            <input type="number" name="bags" step="1" min="1" id="id_quantity"/>
                        </label>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>


                <!-- STEP 4 -->
                <div data-step="3">
                    <h3>Wybierz organizacje, której chcesz pomóc:</h3>
                    <div id="inst">

                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 5 -->
                <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input type="text" name="address" id="id_address" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto <input type="text" name="city" id="id_city" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input type="text" name="postcode" id="id_zip_code" />
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu {{ form.phone_number }}
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input type="date" name="data" id="id_picup_date" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina <input type="time" name="time" id="id_picup_time" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea name="more_info" rows="5" id="id_picup_comment" ></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

                <!-- STEP 6 -->
                <div data-step="5">
                    <h3>Podsumowanie Twojej darowizny</h3>

                    <div class="summary">
                        <div class="form-section">
                            <h4>Oddajesz:</h4>
                            <ul id="summary_1">
                                <li>
                                    <span class="icon icon-bag"></span>
                                    <span class="summary--text" id="quantity-summary"
                                    >4 worki ubrań w dobrym stanie dla dzieci</span
                                    >
                                </li>

                                <li>
                                    <span class="icon icon-hand"></span>
                                    <span class="summary--text"
                                    >Wybrana instytucja</span
                                    >
                                </li>
                            </ul>
                        </div>

                        <div class="form-section form-section--columns">
                            <div class="form-section--column">
                                <h4>Adres odbioru:</h4>
                                <ul>
                                    <li id="street">Prosta 51</li>
                                    <li id="city">Warszawa</li>
                                    <li id="postal">99-098</li>
                                    <li id="phone">123 456 789</li>
                                </ul>
                            </div>

                            <div class="form-section--column">
                                <h4>Termin odbioru:</h4>
                                <ul>
                                    <li id="pickup-date">13/12/2018</li>
                                    <li id="pickup-time">15:40</li>
                                    <li id="pickup-comment">Brak uwag</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="submit" class="btn">Potwierdzam</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

donations/templates/donations/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Witamy!
{% endblock %}

{% block container %}
    <section id="stats" class="stats">
        <div class="container container--85">
            <div class="stats--item">
                <em>{{ donations_quantity }}</em>
                <h3>Oddanych worków</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum
                    tempora!</p>
            </div>

            <div class="stats--item">
                <em>{{ institutions }}</em>
                <h3>Wspartych organizacji</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate
                    quas
                    quam.</p>
            </div>

        </div>
    </section>

    <section id="steps" class="steps">
        <h2>Wystarczą 4 proste kroki</h2>

        <div class="steps--container">
            <div class="steps--item">
                <span class="icon icon--hands"></span>
                <h3>Wybierz rzeczy</h3>
                <p>ubrania, zabawki, sprzęt i inne</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--arrow"></span>
                <h3>Spakuj je</h3>
                <p>skorzystaj z worków na śmieci</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--glasses"></span>
                <h3>Zdecyduj komu chcesz pomóc</h3>
                <p>wybierz zaufane miejsce</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--courier"></span>
                <h3>Zamów kuriera</h3>
                <p>kurier przyjedzie w dogodnym terminie</p>
            </div>
        </div>

        <a href="{% url 'donations:register' %}" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
        <div class="about-us--text">
            <h2>O nas</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt
                libero
                optio esse quisquam illo omnis.</p>
            <img src="{% static '../static/images/signature.svg' %}" class="about-us--text-signature" alt="Signature"/>
        </div>
        <div class="about-us--image"><img src="{% static '../static/images/about-us.jpg' %}" alt="People in circle"/></div>
    </section>

    <section id="help" class="help">
        <h2>Komu pomagamy?</h2>

        <ul class="help--buttons">
            <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
            <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
            <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
        </ul>

        <!-- SLIDE 1 -->
        <div class="help--slides active" data-id="1">
            <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym
                się
                zajmują, komu pomagają i czego potrzebują.</p>

            <ul class="help--slides-items">
                {% for foundation in three_foundations %}
                <li>
                    <div class="col">
                        <div class="title">{{ foundation.name }}</div>
                        <div class="subtitle">{{ foundation.description }}</div>
                    </div>

                    <div class="col">
                        <div class="text">ubrania, jedzenie, sprzęt AGD, meble, zabawki</div>
                    </div>
                </li>
                {% endfor %}
            </ul>

            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
            </ul>
            -->
        </div>


        <!-- SLIDE 2 -->
        <div class="help--slides" data-id="2">
            <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur
                accusamus debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
                quos suscipit corporis!
            </p>
            <ul class="help--slides-items">
                {% for non_gov_org in three_non_gov_org %}
                <li>
                    <div class="col">
                        <div class="title">{{ non_gov_org.name }}</div>
                        <div class="subtitle">{{ non_gov_org.description }}</div>
                    </div>

                    <div class="col">
                        <div class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</div>
                    </div>
                </li>
                {% endfor %}

            </ul>

            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="4">4</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="5">5</a></li>
            </ul>
            -->
        </div>

        <!-- SLIDE 3 -->
        <div class="help--slides" data-id="3">
            <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci
                partiendo
                eos ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
            <ul class="help--slides-items">
                {% for fund_raiser in three_fund_raisers%}
                <li>
                    <div class="col">
                        <div class="title">{{ fund_raiser.name }}</div>
                        <div class="subtitle">{{ fund_raiser.description }}</div>
                    </div>

                    <div class="col">
                        <div class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</div>
                    </div>
                </li>
                {% endfor %}

            </ul>

            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
            </ul>
            -->
        </div>
    </section>
{% endblock %}

donations/templates/donations/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Zaloguj
{% endblock %}

{% block container %}
    <section class="login-page">
        <h2>Zaloguj się</h2>
        <form action="" method="POST">
            {% csrf_token %}
            {% for field in form%}
            <div class="form-group">
                {{ field }}
            {% if field.name == 'password' %}
                <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
            {% endif %}
            </div>
            {% endfor %}

            <div class="form-group form-group--buttons">
                <a href="{% url 'donations:register' %}" class="btn btn--without-border">Załóż konto</a>
                <button class="btn" type="submit">Zaloguj się</button>
            </div>
        </form>
    </section>
{% endblock %}

donations/templates/donations/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Rejestracja
{% endblock %}

{% block container %}
    <section class="login-page">
        <h2>Załóż konto</h2>
        {% if form.errors %}
            {% for error, description in form.errors.items %}
                <div>
                    <strong class="errors">{{ description }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field }}
                </div>
            {% endfor %}

            <div class="form-group form-group--buttons">
                <a href="{% url 'donations:login' %}" class="btn btn--without-border">Zaloguj się</a>
                <button class="btn" type="submit">Załóż konto</button>
            </div>
        </form>
    </section>
{% endblock %}

donations/templates/donations/user-edit-form.html
{% extends 'base.html' %}

{% block title %}
    Ustawienia
{% endblock %}

{% block container %}
    <section class="login-page">
        <h2>Edycja danych</h2>
        {% if form.errors %}
            {% for error, description in form.errors.items %}
                <div>
                    <strong class="errors">{{ description }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field }}
                </div>
            {% endfor %}

            <div class="form-group form-group--buttons">
                <button class="btn" type="submit">Potwierdź</button>
            </div>
        </form>
    </section>
{% endblock %}

donations/templates/donations/user_profile.html
{% extends 'base.html' %}

{% block title %}
 Profil {{ user.name }}
{% endblock %}

{% block container %}
    <section>
        <div>
            <h2>{{ user.first_name }} {{ user.last_name }}
                <p>{{ user.email }}</p>
            </h2>
        </div>
        <div class="container">
            <table>
                    <tr>
                        <th>Instytucja</th>
                        <th>Ilość</th>
                        <th>Data odbioru</th>
                        <th>Kategoria/e</th>
                        <th>Status</th>
                    </tr>
                {% for donation in donations %}
                    <tr {% if donation.is_taken == True %}style="color: silver"{% endif %}>
                        <td>{{ donation.institution }}</td>
                        <td>{{ donation.quantity }}</td>
                        <td>{{ donation.picup_date }}</td>
                        <td>
                            <ul>
                                {% for category in donation.categories.all %}
                                    <li>{{ category.name }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                    {% if donation.is_taken == False %}
                        <td>
                            <a href="{% url 'donations:donation_taken' donation.id %}">
                                <input type="submit" value="Oznacz jako odebrany" data-id="{{ donation.id }}">
                            </a>
                        </td>
                    {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </section>
{% endblock %}