config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('donations.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

donations/urls.py
from django.urls import path

from . import views

app_name = 'donations'

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing_page'),
    path('donation', views.AddDonationView.as_view(), name='add_donation'),
    path('donation-is-taken/<int:donation_id>', views.DonationIsTakenView.as_view(), name='donation_taken'),
    path('donation/success', views.SuccessAddDonationView.as_view(), name='success_add_donation'),
    path('login', views.DonationsLoginView.as_view(), name='login'),
    path('logout', views.DonationsLogoutView.as_view(), name='logout'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('profile', views.UserProfileView.as_view(), name='user_profile'),
    # path('edit', views.edit_user_profile_view, name='user_change'),
]

templates/base.html
{% load static %}
<html lang="pl">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>{% block title %}{% endblock %}</title>

    {% block styles %}
        <link rel="stylesheet" href="{% static '../static/css/style.css' %}"/>
    {% endblock %}

    {% block scripts %}
        <script src="{% static '../static/js/app.js' %}"></script>
    {% endblock %}
</head>
<body>
{% include 'navbar.html' %}

{% block container %}

{% endblock %}

{% include 'footer.html' %}
</body>
</html>

templates/footer.html
{% load static %}
<footer>
    <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
            <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię"/></div>
            <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko"/></div>

            <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

            <button class="btn" type="submit">Wyślij</button>
        </form>
    </div>
    <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2019</span>
        <div class="bottom-line--icons">
            <a href="#" class="btn btn--small"><img src="{% static '../static/images/icon-facebook.svg' %}"/></a>
            <a href="#" class="btn btn--small"><img src="{% static '../static/images/icon-instagram.svg' %}"/></a>
        </div>
    </div>
</footer>

templates/navbar.html
{% load static %}
<header {% if css_class %} class="{{ css_class }}" {% else %}{% endif %}>
    <nav class="container container--70">
        <ul class="nav--actions">
            {% if user.is_authenticated %}
                <li class="logged-user">
                Witaj {{ user.first_name }}
                <ul class="dropdown">
                  <li><a href="{% url 'donations:user_profile' %}">Profil</a></li>
{#                  <li><a href="{% url 'donations:user_change' %}">Ustawienia</a></li>#}
                    {% if user.is_superuser %}
                        <li><a href="{% url 'admin:index' %}">Panel administratora</a></li>
                    {% endif %}
                  <li><a href="{% url 'donations:logout' %}">Wyloguj</a></li>
                </ul>
              </li>
            {% endif %}
            <li><a href="{% url 'donations:login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
            <li><a href="{% url 'donations:register' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
        </ul>

        <ul>
            <li><a href="{% url 'donations:landing_page' %}" class="btn btn--without-border active">Start</a></li>
            <li><a href="{% url 'donations:landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
            <li><a href="{% url 'donations:landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
            <li><a href="{% url 'donations:landing_page' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
            <li><a href="{% url 'donations:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
            <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
    </nav>

    {% if css_class == 'header--main-page' %}
        <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Zacznij pomagać!<br />
            Oddaj niechciane rzeczy w zaufane ręce
          </h1>
        </div>
      </div>
    {% elif css_class == 'header--form-page' %}
        <div class="slogan container container--90" id="form-information">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    {% else %}
        <div>

        </div>
    {% endif %}
</header>